# Generated by Django 5.2.8 on 2025-11-19 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Análisis Matemático I', max_length=200)),
                ('anio_plan', models.PositiveSmallIntegerField(default=1, verbose_name='Año de la carrera')),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, 'Primer cuatrimestre'), (2, 'Segundo cuatrimestre'), (0, 'Anual')], default=0, verbose_name='Cuatrimestre')),
                ('estado', models.CharField(choices=[('AP', 'Aprobada'), ('RP', 'Reprobada'), ('CU', 'Cursando')], default='CU', max_length=2)),
                ('nota_cursada', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de los parciales/TPs', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de examen final o promoción', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlativas', models.ManyToManyField(blank=True, related_name='es_correlativa_de', to='carrera.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['anio_plan', 'nombre'],
            },
        ),
    ]
