# Generated by Django 5.2.8 on 2025-11-19 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_alter_materia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='nota_cursada',
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PAR1', '1er Parcial'), ('PAR2', '2do Parcial'), ('PAR3', '3er Parcial'), ('REC1', 'Recuperatorio 1'), ('REC2', 'Recuperatorio 2'), ('TP', 'Trabajo Práctico'), ('OTRO', 'Otro')], default='PAR1', max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones', models.TextField(blank=True, help_text="Ej: 'Aprobado con lo justo'", max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='carrera.materia')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['fecha', 'nombre'],
            },
        ),
    ]
