# Generated by Django 5.2.8 on 2025-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0003_remove_materia_nota_cursada_evaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['fecha', 'instancia'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='nombre',
            new_name='instancia',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_contenido',
            field=models.CharField(choices=[('T', 'Teoria'), ('P', 'Práctica'), ('TP', 'Teoría y Práctica')], default='T', max_length=50),
        ),
    ]
