# Generated by Django 5.2.8 on 2025-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0004_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(choices=[('AP', 'Aprobada'), ('RP', 'Reprobada'), ('CU', 'Cursando'), ('NP', 'No Iniciada')], default='NP', max_length=2),
        ),
    ]
