# Generated by Django 5.2.8 on 2025-11-20 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0005_alter_materia_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(help_text='Ej: UTN, UBA, UNLP', max_length=100, verbose_name='Facultad / Universidad')),
                ('carrera', models.CharField(help_text='Ej: Ingeniería en Sistemas', max_length=100, verbose_name='Carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
