# Generated by Django 5.2.8 on 2025-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0007_alter_perfil_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='facultad',
            field=models.CharField(choices=[('UTN_FRLP', 'UTN - Facultad Regional La Plata'), ('UNLP_INFO', 'UNLP - Facultad de Informática'), ('UNLP_ING', 'UNLP - Facultad de Ingeniería'), ('UNLP_ECO', 'UNLP - Facultad de Ciencias Económicas'), ('UNLP_EXA', 'UNLP - Facultad de Ciencias Exactas'), ('UNLP_JUR', 'UNLP - Facultad de Ciencias Jurídicas y Sociales'), ('UNLP_MED', 'UNLP - Facultad de Ciencias Médicas'), ('UNLP_ARQ', 'UNLP - Facultad de Arquitectura y Urbanismo'), ('UNLP_ART', 'UNLP - Facultad de Artes'), ('UNLP_AGR', 'UNLP - Facultad de Ciencias Agrarias y Forestales'), ('UNLP_AST', 'UNLP - Facultad de Ciencias Astronómicas y Geofísicas'), ('UNLP_NAT', 'UNLP - Facultad de Ciencias Naturales y Museo'), ('UNLP_VET', 'UNLP - Facultad de Ciencias Veterinarias'), ('UNLP_HUM', 'UNLP - Facultad de Humanidades y Ciencias de la Educación'), ('UNLP_ODO', 'UNLP - Facultad de Odontología'), ('UNLP_PER', 'UNLP - Facultad de Periodismo y Comunicación Social'), ('UNLP_PSI', 'UNLP - Facultad de Psicología'), ('UNLP_TS', 'UNLP - Facultad de Trabajo Social'), ('UCALP', 'Universidad Católica de La Plata'), ('UEST', 'Universidad del Este'), ('OTRA', 'Otra')], default='UTN_FRLP', max_length=100, verbose_name='Facultad'),
        ),
    ]
